### ISSUE TITLE
Wrong stacking of icon at certain display widths

### ISSUE THREAD

**Issue by jhadvig** [openshift/angular-key-value-editor#118] opened 2016-10-03 09:43 UTC
Icons in the editor are not displayed correctly at certain witdhs. eg: 
![screenshot-41](https://cloud.githubusercontent.com/assets/1668218/19033367/50f9e1b8-895e-11e6-9e06-9f743a9f2dc5.png)

**Comment by benjaminapetersen** [comment] 2016-10-31 18:19
Ah, I didn't see this bug come in.

@rhamilto

**Comment by rhamilto** [comment] 2016-10-31 20:10
This bug appears to be specific to Chrome on Linux.  

I am unable to reproduce in Chrome for macOS or Windows.

![macos](https://cloud.githubusercontent.com/assets/895728/19869740/f9afcad0-9f83-11e6-8815-588d14fcaa47.png)
![windows-8 1](https://cloud.githubusercontent.com/assets/895728/19869741/f9b5edca-9f83-11e6-942e-9de71eb8eb0e.png)
![windows-10](https://cloud.githubusercontent.com/assets/895728/19869742/f9b6abd4-9f83-11e6-8d3d-e230bdc7a54b.png)

And I'm unable to reproduce in Firefox for Linux.

![screen shot 2016-10-31 at 4 08 25 pm](https://cloud.githubusercontent.com/assets/895728/19869851/5b7d012e-9f84-11e6-931b-a5bf60017fce.PNG)

Given the bug appears to be specific to Chrome on Linux only when the user zooms 1 step up, I'm inclined to let this one stand.  Thoughts?

**Comment by benjaminapetersen** [comment] 2016-11-01 13:48
So
- Chrome on Linux only
- Zoom 0 fine
- Zoom 1 stacks (bug here)
- Zoom 2+ fine again

Yeah, that def seems like a really weird bug to track down & I'm not sure we could do anything about it to target that specifically.

**Comment by rhamilto** [comment] 2016-11-17 21:07
Closing since this one appears to be OS/browser-specific.

**Closed by rhamilto** 2016-11-17 21:07 UTC
